export const APPROUTES = {
  cardetails: "cardetails",
  receivecar: "receivecar",
  carsmaintenance: "carsmaintenance",
  rentallocations: "rentallocations",
  pricelist: "pricelist",
  reservationlist: "reservationlist",
  reservation: "reservation",
  cars: "cars",
  carslist: "carlist",
  client: "client",
  home: "",
  heroes: "heroes",
  toasters: "toasters",
  inputs: "inputs",
  about: "about",
  aboutus: "about/us",
  aboutversion: "about/version",
  contextmenus: "contextmenus",
  perfectscrollbar: "perfectscrollbar",
  forbidden: "forbidden",
  unauthorized: "unauthorized",
  catchAll: "**",
};
